### ISSUE TITLE
En vrac

### ISSUE THREAD

**Issue by ghost** [mothsART/editInteractiveSVG#1]
Bonjour,

Je viens d'installer le logiciel, test avec firefox quantum.

- au local j'ai fait une installation sous Ubuntu, pour le ppa il manque une information dans la doc à savoir un sudo apt-get install edit-interactive-svg. Au local, je charge un exemple, il m'est impossible de déplacer un objet créé y compris sur un exemple. 
- sur ton site, si on lance la démo, j'ai fait celle du campement, au retour de l'image suite à une transition dans l'édition, l'image n'est plus centrée mais complètement décalée par rapport à la position de la transition choisie. 

![selection_001](https://user-images.githubusercontent.com/3888577/34651391-12b75f24-f3d0-11e7-8236-445a552b59cf.png)

**Comment by mothsART** [comment]
Déjà, merci pour tes retours !
* Effectivement, je vais compléter la doc.
* Je constate bien le décalage mais uniquement sur Firefox : ça sera corrigé dans la version rc3.
* Pour le déplacement d'objet, j'ai effectivement un comportement assez étrange sur Firefox : il faut cliquer, relacher en dehors de la zone de l'indice pour drag et un second clic pour drop.
J'ai pas vraiment trouvé de solution plus élégante dans ce navigateur.
Je vais tenter un post sur un forum car je sèche un peu sur ce point.
 C'est bien ce ça que tu parles ?
(Par sécurité, je vais m'installer une version de firefox quantum.)

**Comment by ghost** [comment]
tu as dans les commentaires de linuxfr quelqu'un qui retrouve le même problème que moi sur le décalage. Je t'invite à ... inviter les gens ici sinon tu vas devoir répondre à deux endroits en même temps. 

Impossible de déplacer les numéros avec Firefox c'est possible avec Chromium.

**Comment by mothsART** [comment]
J'ai cru également à la première lecture que le soucis de décalage étair le même.
En réalité, tu parles d'un vrai disfonctionnement propre à Firefox lors du retour au mode d'édition.
En revanche, le commentaire sur Linuxfr parle d'un soucis de décalage dans le mode de visualisation. (ou le fichier final)

Merci du conseil mais j'ai malheureusement trop peu de personne qui s'intéresse réellement à mon projet pour imposer quoi que ce soit.
Merci néanmoins à toi de jouer le jeu.

**Comment by ghost** [comment]
t'inquiète pas, en remontée de bug, je suis champion. J'attends que tu le rendes utilisable sur Firefox et je ferai de la propagande pour faire venir du monde.

**Comment by mothsART** [comment]
Je viens de corriger tes 2 bugs. Le pack, la mise à jour de la démo devrait suivre :yum:

**Comment by ghost** [comment]
tu mets à jour le ppa ou je prends directement dans le github ?

**Comment by mothsART** [comment]
Si tu veux valider, le mieux est de récup les sources et visualiser index.html sous firefox.
Ca m'évites de faire des packs à la hative et d'y incorporer des faux-positifs.

**Comment by ghost** [comment]
testé sur un hébergement personnel et avec firefox sur l'exemple des hommes des cavernes, ça passe
