### ISSUE TITLE
Utilisation des touches du clavier pour passer d'un élément à l'autre

### ISSUE THREAD

**Issue by ghost** [mothsART/editInteractiveSVG#5]
Tout est dans le titre.

**Comment by mothsART** [comment]
Fonctionnalité ajouté. (ouais, plus d'1 an après)
Un petit menu d'aide (qui  se déclenche en cliquant sur un petit bouton d'aide et qui se matérialise par un dialogue) permet de connaitre les différents raccourcis disponibles.
