### ISSUE TITLE
Impossible de déplacer la légende lors d'un chargement d'une image personnelle

### ISSUE THREAD

**Issue by ghost** [mothsART/editInteractiveSVG#6]
Même problème qu'à l'origine, si le bug est corrigé pour les exemples, je n'avais pas fait le test avec une image personnelle. A l'ajout de la transition je me retrouve avec un doigt pour pointer et pas une main pour déplacer. 

Il serait aussi intéressant de pouvoir choisir la taille de l'image svg sélectionnée de base dans l'éditeur.

**Comment by mothsART** [comment]
- A l'ajout de la transition = cocher le bouton "activer" ?
Si oui, je n'ai volontairement pas donné la possibilité de déplacer un indice dans le cadre d'un zoom.
On va dire que c'est : 
1. historique : j'ai changé 3 fois l'arborescence html de mes indices et à chaque fois je m'arrachais les cheveux sur ce calcul. (avec le responsive, je dois convertir des déplacements de la souris en pixel en une valeur en pourcentage tout en tenant compte des données de translation initiales du document, la valeur de zoom d'un indice et ses coordonnées).
2. Ca nécessite de réfléchir au drag and drop d'un indice sur un svg zoomé : que fait-on si l'on s'approche des bords du cadre ? on bloque l'indice ou on se déplace sur l'image ?

Ma crainte derrière ce dev c'est les effets de bord sur une partie désormais stable à mon sens.
Je préfère donc le réserver pour une 1.1 plutôt que différer grandement la sortie d'une 1.0 pour une fonctionnalité non bloquante.

- Choisir la taille ?

Je peine à comprendre : pour moi, le svg n'a pas de taille à proprement parlé vu que justement, c'est du vectoriel.
En revanche, il a un ratio (diff entre hauteur et largeur).
Un travail de fond à été effectué à ce niveau pour que le fichier svg occupe constamment l'espace le plus grand dans la zone d'édition afin de garantir un confort optimal.

**Comment by ghost** [comment]
On ne s'est peut être pas être pas compris. 

* voici mon document de travail, quand je mets la souris sur le 1 je devrais avoir la main. Je ne peux pas déplacer le 1
* je charge mon image et je trouve qu'elle est petite. Nous sommes d'accord, le svg n'a pas de taille. Mais moi j'aimerai bien qu'il soit plus gros, comment je fais ? 

![edit interactive svg - mozilla firefox_010](https://user-images.githubusercontent.com/3888577/34914560-2f4067a4-f915-11e7-9749-87c5134dd4dc.png)

l'adresse de l'image de travail : https://commons.wikimedia.org/wiki/File:Volcano.svg

**Comment by mothsART** [comment]
Merci pour l'exemple.

Effectivement, on ne pouvait pas se comprendre.
Tu viens de mettre le doigt sur un bug spécifique à Firefox et lié à la nature du fichier importé.(pas d'attribut viewbox dans le svg : le fichier est sans doute ancien car mes versions de Inkscape ne me permette pas de créer de svg sans renseigner de viewbox)
En effet, pour avoir l'accès aux tailles du viewbox à l'import, on a une api de ce type :
svg.viewBox.baseVal;
Si l'attribut "viewbox" n'existe pas dans le noeud svg, chrome en déduit qu'il prend les tailles de l'illustration au complet.
En revanche, firefox par du constat opposé : pas renseigné donc je ne sais pas => valeur null.

Ce soucis bloque à l'import du fichier et empèche par conséquent le resize de l'image (qui parait petite du coup) et l'attribution des évènements : pas de drag and drop.

Je viens d'envoyer le correctif correspondant !

**Comment by ghost** [comment]
je confirme la correction
